Folio 2641 Edge Modules Ephemeral and Vault deployment
folio-org/folio-ansible pull request #411
Opened 2021-01-19 06:18 UTC by mbstacy

The following PR is for edge modules that use edge-common. edge-sip2 is not included at this time within this role. The default secure store is Ephemeral with the use of the variable `institutional_users`. Refer to `vault-readme.md`  for using Vault as the secret store.

2021-01-19 16:14 UTC, wafschneider reviewed
I have some concerns with the updates you made to the defaults, as those can break existing configurations. Otherwise this seems sensible.

If the defaults were changed to make it more convenient to use the role to only deploy edge modules, remember that you can always set those variables when invoking the role in a playbook or on the `ansible-playbook` command line.

2021-01-19 16:14 UTC, wafschneider commented on roles/module-kubernetes/defaults/main.yml
> +kubeconfig: ~/.kube/config-test
Was this intended? Seems like it might break existing configurations

2021-01-19 16:14 UTC, wafschneider commented on roles/module-kubernetes/defaults/main.yml
> +okapi_pull: no
Why change these defaults? If changing defaults, you'll need to update the README, as well

2021-01-19 16:28 UTC, mbstacy commented on roles/module-kubernetes/defaults/main.yml
> +kubeconfig: ~/.kube/config-test
@wafschneider yes, that was a correction that I do on my system. I tested the role on my test cluster in which the config file is `config-test`. I will revert back to `config`.

2021-01-19 16:29 UTC, mbstacy commented on roles/module-kubernetes/defaults/main.yml
> +okapi_pull: no
Same on this item. I turn off the `okapi_pull` when testing. I will revert these items! Thanks @wafschneider

2021-01-19 20:07 UTC, wafschneider requested changes
Sorry for this, but since the file name is "ephemeral" (which is spelled correctly), all the reference in documentation definitely need to be consistent ("ephemiral" is sprinkled throughout).

Once that is corrected, I'm happy. Sorry to pick nits.

2021-01-19 20:07 UTC, wafschneider commented on roles/module-kubernetes/README.md
> +Ansible current role can handle `Vault` or `Ephemiral` Secure Store. The default is Ephemiral and uses `institutional_users` variable to set Institutional Users. Please refer to [Edge Vault Readme](v
Should be "Ephemeral"

2021-01-19 20:07 UTC, wafschneider commented on roles/module-kubernetes/README.md
> +edge_secure_store: Vault or Ephemiral(Default)
Again, should be "Ephemeral"

2021-01-20 19:53 UTC, merged

2021-01-20 19:53 UTC, mbstacy commented
Fixed the changes to the default variables and the Spelling error of Ephemeral within the readme.