Update post-config-entries role to use new Okapi smtp configuration API
folio-org/folio-ansible pull request #548
Opened 2023-04-05 13:50 UTC by david-igbinedion

2023-04-05 15:18 UTC, funkymalc approved these changes
Looks good to me @david-igbinedion.   Assuming it's been tested,  go ahead and merge to master.

2023-04-05 18:25 UTC, wafschneider approved these changes
This looks good to me, as well -- we should test before merging, though. @david-igbinedion let me know if you need help testing.

One thing to consider is if we should make the reply-to setting optional. It was added after this role was originally created and probably should have been made optional to avoid breaking existing configurations. Could be done as part of the template, something like:
```
{%if email_reply_to|default(false) %}
  "emailHeaders": [ ... ]
{% endif %}
```

2023-04-05 19:41 UTC, wafschneider requested changes
Actually, I just noticed a problem (which I'm sure is in part caused by a confusing task name `post mod-email configuration`). This role was actually designed to post an arbitrary set of configuration entries to the `/configurations/entries` endpoint. It was mostly used for SMTP settings, but is also used for a mod-users-bl setting, and could be used for others.

So instead of just changing the task to post to `/smtp/configuration`, you actually need to preserve the original task (without the email config entries, leaving just the mod-users-bl entry), and add a new task to post SMTP settings to the new endpoint.

2023-04-06 10:33 UTC, david-igbinedion commented
@wafschneider I've separated the post config entries task from the post smtp task and also made reply-to optional. Please review.

2023-04-06 23:01 UTC, wafschneider requested changes
I think with the one change of the filename this will be good to go. Thank you!

2023-04-06 23:01 UTC, wafschneider commented on roles/post-config-entries/templates/email_config.json
Can this file be given a j2 extension per the convention in this repository?

Might not be the best convention, to be fair, but I think it is consistent across the roles in this repo.

2023-04-06 23:30 UTC, wafschneider commented on roles/post-config-entries/tasks/main.yml
> +
To keep this backward compatible, I think you can add:
```
  when: email_entry_list|default(false)
```

That should keep existing playbooks from breaking until they are updated to pass the new variable.

2023-04-11 07:35 UTC, david-igbinedion commented on roles/post-config-entries/tasks/main.yml
> +
Done

2023-04-11 07:56 UTC, merged